export const common = {
  color: '颜色',
  width: '宽度',
  height: '高度',
  type: '类型',
  show: '显示/隐藏',
  offsetX: '偏移X',
  offsetY: '偏移Y',
  rotate: '旋转角度',
  shadowBlur: '阴影模糊',
  shadowColor: '阴影颜色',
  shadowOffsetX: '阴影偏移X',
  shadowOffsetY: '阴影偏移Y',
  opacity: '透明度',
  symbol: '标记图形',
  symbolSize: '图形大小',
  symbolRotate: '图形旋转',
  margin: '外边距',
  left: '左边距',
  top: '上边距',
  bottom: '下边距',
  right: '右边距',
  backgroundColor: '背景颜色',
  borderColor: '边框颜色',
  borderWidth: '边框宽度',
  borderType: '边框类型',
  orient: '排列方向',
  position: '位置',
  offset: '偏移',
  align: '对齐方式',
  length: '长度',
}

export const label = {
  show: '是否显示',
  rotate: '旋转角度',
  offsetX: '字体偏移X',
  offsetY: '字体偏移Y',
  margin: '外边距',
  color: '字体颜色',
  fontStyle: '字体风格',
  fontSize: '字体大小',
  fontWeight: '字体粗细',
  align: '字体对齐',
  textBorderColor: '字体边框颜色',
  textBorderWidth: '字体边框宽度',
  textBorderType: '字体边框类型',
  minMargin: '字体间距',
  position: '字体位置',
  fontFamily: '字体类型',
  backgroundColor: '背景颜色',
  borderColor: '边框颜色',
  borderWidth: '边框宽度',
  borderType: '边框类型',
  shadowColor: '阴影颜色',
  shadowBlur: '阴影模糊',
  shadowOffsetX: '阴影偏移X',
  shadowOffsetY: '阴影偏移Y',
  textShadowColor: '字体阴影颜色',
  textShadowBlur: '字体阴影模糊',
  textShadowOffsetX: '字体阴影偏移X',
  textShadowOffsetY: '字体阴影偏移Y'
}

export const candlestick_itemStyle = {
  color: '阳线颜色',
  color0: '阴线颜色',
  borderColor: '边框颜色',
  borderColor0: '描边颜色',
  borderWidth: '边框宽度',
  shadowBlur: '阴影模糊',
  shadowColor: '阴影颜色',
  shadowOffsetX: '阴影偏移X',
  shadowOffsetY: '阴影偏移Y',
  opacity: '透明度',
}

export const radar = {
  shape: '雷达形状',
  nameGap: '名称距离',
  splitNumber: '指示器段数',
  centerX: 'X偏移(%)',
  centerY: 'Y偏移(%)',
  radius: '雷达大小(%)',
  startAngle: '旋转角度',
}